name: Release library

on:
  push:
    branches:
      - 'releases/v*'

jobs:
  update-publish:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: https://npm.pkg.github.com/

      - name: Parse version info from branch name
        run: |
          VERSION=${GITHUB_REF_NAME:10}
          echo "version=$VERSION" >> $GITHUB_ENV

      - run: npm version ${{ env.version }} --no-git-tag-version --allow-same-version

      - continue-on-error: true
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./package.json
          git commit -m "bump package.json version to ${{ env.version }}"
          git push

      - run: npm install

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
